### ISSUE TITLE
You should really add Enpass

### ISSUE THREAD

**Issue by EugenMayer** [jikamens/password-manager-comparer#2]
Hi, cool list!

I would suggest adding Enpass to the list, since it is very feature rich, 100% offline, all platforms including all mobile platforms and is probably one of the be(st)tter Linux password manager.

No hard feelings, i just think it should be part of the gang for good comparison.

**Comment by jikamens** [comment]
As you may have noticed, all of the password managers evaluated here are online password managers. That is usually a hard requirement in any business environment, since it's hard enough to get a whole company full of people to use an online password manager reliably, let alone get them to use a password manager and also get it to properly sync among all their devices. This evaluation is targeted primarily at people looking to choose a password manager for deploying in a business environment, so it does not consider Enpass or other offline password managers.

I will consider a PR to add evaluation of Enpass and/or other password managers as long as it adds "Online Sync" as one of the listed features so that it is easy for people who require online sync to exclude Enpass and other offline password managers from the grid.

Because I personally have no desire or intention to use an offline password manager, I am not going to perform the evaluation myself.

**Comment by EugenMayer** [comment]
Well we are using Enpass in such a `business environment` because using a online password manager would be the last thing we would do, at least remote cloud hosted. ( bitwarden could be a choice though ).

Enpass offers sharing, multiple faults and syncs based on files - so you could use anything. From a network share to a dropbox/nextcloud/webdav/resilio sync/ds file/<whatever you can sync files with>

This means, common passwords can be shared, while having his own vault up. The mobile devices use one of the protocols above to sync it. 

Anyway, not here to convince anybody or make somewhat of a religious statement - i was not aware of your "goal" and with my statement above i wanted to just describe, that Enpass ( or other file based ) can be used in your desired environment without big issues.
